### ISSUE TITLE
cannot find module "password-hash"

### ISSUE THREAD

**Issue by shrutipant7** [sanattaori/techdot#3]
On running the project using command-node index.js, the above written error is appearing on my screen.
![Untitled](https://user-images.githubusercontent.com/29400237/55431029-17e38280-55ad-11e9-9bf6-257816c98a6d.png)

**Comment by sanattaori** [comment]
npm install password-hash

**Comment by kaarthigaAyyappan** [comment]
Admin password

**Comment by kaarthigaAyyappan** [comment]
How to chnge tht
