### ISSUE TITLE
can not find module cookie-parser

### ISSUE THREAD

**Issue by shrutipant7** [sanattaori/techdot#4]
![Untitled](https://user-images.githubusercontent.com/29400237/56836432-d8027900-6894-11e9-91a9-067194b60583.png)

**Comment by sanattaori** [comment]
just run npm install <dependency name> to install any missing dependency,
in this case `npm install cookie-parser`

**Comment by shrutipant7** [comment]
My code is showing errors while compiling which reads "Extra non whitespace
after JSON value ". Please help.

**Comment by shrutipant7** [comment]
Also since it was showing errors installing testrpc, I have used
ganache-cli as the command prompt showed this package name has now been
changed to ganache-cli.

**Comment by sanattaori** [comment]
Maybe different version of solc cause this problem 
try changing code that reads solc code 
checkout https://ethereum.stackexchange.com/questions/62802/remix-is-compiling-the-smart-contract-but-not-solc-command
and yes test rpc package name is now changed, it may show warning but the ganache-cli will be installed with no error

**Comment by shrutipant7** [comment]
here is attached the error trace when compiling the code

**Comment by sanattaori** [comment]
Can you please share the snap of compiled error code where "Extra non whitespace
after JSON value" is written, cause i cannot see the snap.

**Comment by shrutipant7** [comment]
Got that one solved by adjusting compiler version. But getting a different
one now.

**Comment by shrutipant7** [comment]
What to write in username and password field?

**Comment by shrutipant7** [comment]
Got it

**Comment by shrutipant7** [comment]
Thanks for your support. The project is running fine now. One last query :
how do I get to see how many votes each candidate has got?
